In [8]:
import numpy as np

N = 6
a = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        a[i, j] = 3. / (0.6*i*j + 1)
print(np.linalg.matrix_rank(a))
a[1, 1] = 3

def LUP(L, U, P):
    return L @ U @ np.linalg.inv(P)
def diy_LU2(a):
    N = a.shape[0]
    U = a.copy()
    P = np.eye(N)
    L = np.eye(N)
    for k in range(0, N - 1):
        max_el = k + np.argmax(abs(U[k:, k])) 
        if max_el != k:
            P_temp = np.eye(N)
            P_temp[k,k], P_temp[max_el,max_el] = 0, 0
            P_temp[k,max_el], P_temp[max_el,k] = 1, 1
            P = P_temp @ P
            L = P_temp @ L
            U = P_temp @ U
        lam = np.eye(N)
        gamma = U[k+1:, k] / U[k, k]
        lam[k+1:, k] = -gamma
        U = lam @ U
        L = lam @ L
    L = np.linalg.inv(L @ np.linalg.inv(P))
    return P, L, U

np.set_printoptions(precision=3)

P, L, U = diy_LU2(a)
print (P, "\n"*2, L, "\n"*2, U, "\n")
print(L @ U - P @ a, "\n")
print (LUP(L, U, P), "\n")
print (a1)

P, L, U = diy_LU2(a)
print (P, "\n"*2, L, "\n"*2, U, "\n")
print(L @ U - P @ a, "\n")
print (LUP(L, U, P), "\n")
print (a)

6
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]] 

 [[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    0.    1.    0.    0.    0.   ]
 [1.    0.727 0.151 1.    0.    0.   ]
 [1.    0.857 0.088 0.514 1.    0.   ]
 [1.    0.941 0.038 0.208 0.641 1.   ]] 

 [[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -2.250e+00 -2.571e+00 -2.700e+00 -2.769e+00 -2.812e+00]
 [ 0.000e+00  0.000e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  2.776e-17 -9.247e-02 -1.485e-01 -1.856e-01]
 [ 0.000e+00  1.110e-16 -1.427e-17 -4.160e-18  1.841e-03  3.821e-03]
 [ 0.000e+00 -1.267e-16  3.391e-18  2.669e-18  0.000e+00 -1.233e-05]] 

[[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00 -1.665e-16 -1.665e-16  5.551e-17  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.0